ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS tax_calculation_type TEXT DEFAULT 'exclude',
  ADD COLUMN IF NOT EXISTS has_ppn BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_pph BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pph_rate NUMERIC DEFAULT 2,
  ADD COLUMN IF NOT EXISTS pph_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dpp_amount NUMERIC DEFAULT 0;
